### ISSUE TITLE
CrossQuantilogram as cq

### ISSUE THREAD

**Issue by Rfileforme88** [cran/quantilogram#1]
I have been trying to  import CQ , but in vain. Below are my problem. Plz help. Thanks. 

import pandas as mypf
import numpy as mynp
import matplotlib.pyplot as myplot
import CrossQuantilogram as cq
ModuleNotFoundError                       Traceback (most recent call last)
C:\Users\ECONOM~1\AppData\Local\Temp/ipykernel_7860/1289324908.py in <module>
      2 import numpy as mynp
      3 import matplotlib.pyplot as myplot
----> 4 import CrossQuantilogram as cq

ModuleNotFoundError: No module named 'CrossQuantilogram'

import CrossQuantilogram as cq

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Rfileforme88** [comment]
Thanks. Surly.
